// <auto-generated />
namespace Wiky_ASP_CodeFirst.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Add_constraint : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add_constraint));
        
        string IMigrationMetadata.Id
        {
            get { return "201809181309193_Add_constraint"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
